---
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-npm-deps-{{ checksum "package-lock.json" }}-{{ .Branch }}
            - v1-npm-deps-{{ checksum "package-lock.json" }}
      - run:
          name: Install
          command: npm ci
      - save_cache:
          paths:
            - ~/.npm
          key: v1-npm-deps-{{ checksum "package-lock.json" }}-{{ .Branch }}
      - run:
          name: Test
          command: npm t
      - run:
          name: Release
          command: npm run semantic-release || true
